import {CountryModel} from '../phone-tokens';

export const DEFAULT_COUNTRY_LIST: CountryModel[] = [
    {name: 'Afghanistan', code: 'AF', phoneNumberCode: '+93'},
    {name: 'Albania', code: 'AL', phoneNumberCode: '+355'}, {name: 'Algeria', code: 'DZ', phoneNumberCode: '+213'},
    {name: 'American Samoa', code: 'AS', phoneNumberCode: '+1 684'}, {name: 'Andorra', code: 'AD', phoneNumberCode: '+376'},
    {name: 'Angola', code: 'AO', phoneNumberCode: '+244'}, {name: 'Anguilla', code: 'AI', phoneNumberCode: '+1 264'},
    // {name: 'Antarctica', code: 'AQ' as CountryCode, phoneNumberCode: '+672'},
    {name: 'Argentina', code: 'AR', phoneNumberCode: '+54'},
    {name: 'Armenia', code: 'AM', phoneNumberCode: '+374'}, {name: 'Aruba', code: 'AW', phoneNumberCode: '+297'},
    {name: 'Australia', code: 'AU', phoneNumberCode: '+61'}, {name: 'Austria', code: 'AT', phoneNumberCode: '+43'},
    {name: 'Azerbaijan', code: 'AZ', phoneNumberCode: '+994'}, {name: 'Bahamas', code: 'BS', phoneNumberCode: '+1'},
    {name: 'Bahrain', code: 'BH', phoneNumberCode: '+973'}, {name: 'Bangladesh', code: 'BD', phoneNumberCode: '+880'},
    {name: 'Barbados', code: 'BB', phoneNumberCode: '+1'}, {name: 'Belarus', code: 'BY', phoneNumberCode: '+375'},
    {name: 'Belgium', code: 'BE', phoneNumberCode: '+32'}, {name: 'Belize', code: 'BZ', phoneNumberCode: '+501'},
    {name: 'Benin', code: 'BJ', phoneNumberCode: '+229'}, {name: 'Bermuda', code: 'BM', phoneNumberCode: '+1'},
    {name: 'Bhutan', code: 'BT', phoneNumberCode: '+975'}, {name: 'Bolivia', code: 'BO', phoneNumberCode: '+591'},
    {name: 'Bosnia and Herzegovina', code: 'BA', phoneNumberCode: '+387'},
    {name: 'Botswana', code: 'BW', phoneNumberCode: '+267'}, {name: 'Brazil', code: 'BR', phoneNumberCode: '+55'},
    {name: 'British Virgin Islands', code: 'VG', phoneNumberCode: '+1 284'},
    {name: 'Brunei', code: 'BN', phoneNumberCode: '+673'}, {name: 'Bulgaria', code: 'BG', phoneNumberCode: '+359'},
    {name: 'Burkina Faso', code: 'BF', phoneNumberCode: '+226'}, {name: 'Burundi', code: 'BI', phoneNumberCode: '+257'},
    {name: 'Cambodia', code: 'KH', phoneNumberCode: '+855'}, {name: 'Cameroon', code: 'CM', phoneNumberCode: '+237'},
    {name: 'Canada', code: 'CA', phoneNumberCode: '+1'}, {name: 'Cape Verde', code: 'CV', phoneNumberCode: '+238'},
    {name: 'Cayman Islands', code: 'KY', phoneNumberCode: '+1-345'},
    {name: 'Central African Republic', code: 'CF', phoneNumberCode: '+236'},
    {name: 'Chile', code: 'CL', phoneNumberCode: '+56'}, {name: 'China', code: 'CN', phoneNumberCode: '+86'},
    {name: 'Colombia', code: 'CO', phoneNumberCode: '+57'}, {name: 'Comoros', code: 'KM', phoneNumberCode: '+269'},
    {name: 'Cook Islands', code: 'CK', phoneNumberCode: '+682'}, {name: 'Costa Rica', code: 'CR', phoneNumberCode: '+506'},
    {name: 'Croatia', code: 'HR', phoneNumberCode: '+385'}, {name: 'Cuba', code: 'CU', phoneNumberCode: '+53'},
    {name: 'Curacao', code: 'CW', phoneNumberCode: '+599'}, {name: 'Cyprus', code: 'CY', phoneNumberCode: '+357'},
    {name: 'Czech Republic', code: 'CZ', phoneNumberCode: '+420'},
    {name: 'Democratic Republic of Congo', code: 'CD', phoneNumberCode: '+243'},
    {name: 'Denmark', code: 'DK', phoneNumberCode: '+45'}, {name: 'Djibouti', code: 'DJ', phoneNumberCode: '+253'},
    {name: 'Dominica', code: 'DM', phoneNumberCode: '+1'}, {name: 'Dominican Republic', code: 'DO', phoneNumberCode: '+1'},
    {name: 'East Timor', code: 'TL', phoneNumberCode: '+670'}, {name: 'Ecuador', code: 'EC', phoneNumberCode: '+593'},
    {name: 'Egypt', code: 'EG', phoneNumberCode: '+20'}, {name: 'El Salvador', code: 'SV', phoneNumberCode: '+503'},
    {name: 'Equatorial Guinea', code: 'GQ', phoneNumberCode: '+240'}, {name: 'Eritrea', code: 'ER', phoneNumberCode: '+291'},
    {name: 'Estonia', code: 'EE', phoneNumberCode: '+372'}, {name: 'Ethiopia', code: 'ET', phoneNumberCode: '+251'},
    {name: 'Falkland Islands', code: 'FK', phoneNumberCode: '+500'},
    {name: 'Faroe Islands', code: 'FO', phoneNumberCode: '+298'}, {name: 'Fiji', code: 'FJ', phoneNumberCode: '+679'},
    {name: 'Finland', code: 'FI', phoneNumberCode: '+358'}, {name: 'France', code: 'FR', phoneNumberCode: '+33'},
    {name: 'French Polynesia', code: 'PF', phoneNumberCode: '+689'}, {name: 'Gabon', code: 'GA', phoneNumberCode: '+241'},
    {name: 'Gambia', code: 'GM', phoneNumberCode: '+220'}, {name: 'Georgia', code: 'GE', phoneNumberCode: '+995'},
    {name: 'Germany', code: 'DE', phoneNumberCode: '+49'}, {name: 'Ghana', code: 'GH', phoneNumberCode: '+233'},
    {name: 'Gibraltar', code: 'GI', phoneNumberCode: '+350'}, {name: 'Greece', code: 'GR', phoneNumberCode: '+30'},
    {name: 'Greenland', code: 'GL', phoneNumberCode: '+299'}, {name: 'Guadeloupe', code: 'GP', phoneNumberCode: '+590'},
    {name: 'Guam', code: 'GU', phoneNumberCode: '+1 671'}, {name: 'Guatemala', code: 'GT', phoneNumberCode: '+502'},
    {name: 'Guinea', code: 'GN', phoneNumberCode: '+224'}, {name: 'Guinea-Bissau', code: 'GW', phoneNumberCode: '+245'},
    {name: 'Guyana', code: 'GY', phoneNumberCode: '+592'}, {name: 'Haiti', code: 'HT', phoneNumberCode: '+509'},
    {name: 'Honduras', code: 'HN', phoneNumberCode: '+504'}, {name: 'Hong Kong', code: 'HK', phoneNumberCode: '+852'},
    {name: 'Hungary', code: 'HU', phoneNumberCode: '+36'}, {name: 'Iceland', code: 'IS', phoneNumberCode: '+354'},
    {name: 'India', code: 'IN', phoneNumberCode: '+91'}, {name: 'Indonesia', code: 'ID', phoneNumberCode: '+62'},
    {name: 'Iran', code: 'IR', phoneNumberCode: '+98'}, {name: 'Iraq', code: 'IQ', phoneNumberCode: '+964'},
    {name: 'Ireland', code: 'IE', phoneNumberCode: '+353'}, {name: 'Isle of Man', code: 'IM', phoneNumberCode: '+44'},
    {name: 'Israel', code: 'IL', phoneNumberCode: '+972'}, {name: 'Italy', code: 'IT', phoneNumberCode: '+39'},
    {name: 'Ivory Coast', code: 'CI', phoneNumberCode: '+225'}, {name: 'Jamaica', code: 'JM', phoneNumberCode: '+1'},
    {name: 'Japan', code: 'JP', phoneNumberCode: '+81'}, {name: 'Jordan', code: 'JO', phoneNumberCode: '+962'},
    {name: 'Kazakhstan', code: 'KZ', phoneNumberCode: '+7'}, {name: 'Kenya', code: 'KE', phoneNumberCode: '+254'},
    {name: 'Kiribati', code: 'KI', phoneNumberCode: '+686'}, {name: 'Kosovo', code: 'XK', phoneNumberCode: '+381'},
    {name: 'Kuwait', code: 'KW', phoneNumberCode: '+965'}, {name: 'Kyrgyzstan', code: 'KG', phoneNumberCode: '+996'},
    {name: 'Laos', code: 'LA', phoneNumberCode: '+856'}, {name: 'Latvia', code: 'LV', phoneNumberCode: '+371'},
    {name: 'Lebanon', code: 'LB', phoneNumberCode: '+961'}, {name: 'Lesotho', code: 'LS', phoneNumberCode: '+266'},
    {name: 'Liberia', code: 'LR', phoneNumberCode: '+231'}, {name: 'Libya', code: 'LY', phoneNumberCode: '+218'},
    {name: 'Liechtenstein', code: 'LI', phoneNumberCode: '+423'}, {name: 'Lithuania', code: 'LT', phoneNumberCode: '+370'},
    {name: 'Luxembourg', code: 'LU', phoneNumberCode: '+352'}, {name: 'Macau', code: 'MO', phoneNumberCode: '+853'},
    {name: 'Macedonia', code: 'MK', phoneNumberCode: '+389'}, {name: 'Madagascar', code: 'MG', phoneNumberCode: '+261'},
    {name: 'Malawi', code: 'MW', phoneNumberCode: '+265'}, {name: 'Malaysia', code: 'MY', phoneNumberCode: '+60'},
    {name: 'Maldives', code: 'MV', phoneNumberCode: '+960'}, {name: 'Mali', code: 'ML', phoneNumberCode: '+223'},
    {name: 'Malta', code: 'MT', phoneNumberCode: '+356'}, {name: 'Marshall Islands', code: 'MH', phoneNumberCode: '+692'},
    {name: 'Mauritania', code: 'MR', phoneNumberCode: '+222'}, {name: 'Mauritius', code: 'MU', phoneNumberCode: '+230'},
    {name: 'Mexico', code: 'MX', phoneNumberCode: '+52'}, {name: 'Micronesia', code: 'FM', phoneNumberCode: '+691'},
    {name: 'Moldova', code: 'MD', phoneNumberCode: '+373'}, {name: 'Monaco', code: 'MC', phoneNumberCode: '+377'},
    {name: 'Mongolia', code: 'MN', phoneNumberCode: '+976'}, {name: 'Montenegro', code: 'ME', phoneNumberCode: '+382'},
    {name: 'Montserrat', code: 'MS', phoneNumberCode: '+1 664'}, {name: 'Morocco', code: 'MA', phoneNumberCode: '+212'},
    {name: 'Mozambique', code: 'MZ', phoneNumberCode: '+258'}, {name: 'Myanmar [Burma]', code: 'MM', phoneNumberCode: '+95'},
    {name: 'Namibia', code: 'NA', phoneNumberCode: '+264'}, {name: 'Nauru', code: 'NR', phoneNumberCode: '+674'},
    {name: 'Nepal', code: 'NP', phoneNumberCode: '+977'}, {name: 'Netherlands', code: 'NL', phoneNumberCode: '+31'},
    {name: 'New Caledonia', code: 'NC', phoneNumberCode: '+687'}, {name: 'New Zealand', code: 'NZ', phoneNumberCode: '+64'},
    {name: 'Nicaragua', code: 'NI', phoneNumberCode: '+505'}, {name: 'Niger', code: 'NE', phoneNumberCode: '+227'},
    {name: 'Nigeria', code: 'NG', phoneNumberCode: '+234'}, {name: 'Niue', code: 'NU', phoneNumberCode: '+683'},
    {name: 'Norfolk Island', code: 'NF', phoneNumberCode: '+672'}, {name: 'North Korea', code: 'KP', phoneNumberCode: '+850'},
    {name: 'Northern Mariana Islands', code: 'MP', phoneNumberCode: '+1 670'},
    {name: 'Norway', code: 'NO', phoneNumberCode: '+47'}, {name: 'Oman', code: 'OM', phoneNumberCode: '+968'},
    {name: 'Pakistan', code: 'PK', phoneNumberCode: '+92'}, {name: 'Palau', code: 'PW', phoneNumberCode: '+680'},
    {name: 'Panama', code: 'PA', phoneNumberCode: '+507'}, {name: 'Papua New Guinea', code: 'PG', phoneNumberCode: '+675'},
    {name: 'Paraguay', code: 'PY', phoneNumberCode: '+595'}, {name: 'Peru', code: 'PE', phoneNumberCode: '+51'},
    {name: 'Philippines', code: 'PH', phoneNumberCode: '+63'},
    // {name: 'Pitcairn Islands', code: 'PN' as CountryCode, phoneNumberCode: '+870'},
    {name: 'Poland', code: 'PL', phoneNumberCode: '+48'}, {name: 'Portugal', code: 'PT', phoneNumberCode: '+351'},
    {name: 'Puerto Rico', code: 'PR', phoneNumberCode: '+1'}, {name: 'Qatar', code: 'QA', phoneNumberCode: '+974'},
    {name: 'Republic of the Congo', code: 'CG', phoneNumberCode: '+242'},
    {name: 'Reunion', code: 'RE', phoneNumberCode: '+262'}, {name: 'Romania', code: 'RO', phoneNumberCode: '+40'},
    {name: 'Russia', code: 'RU', phoneNumberCode: '+7'}, {name: 'Rwanda', code: 'RW', phoneNumberCode: '+250'},
    {name: 'Saint Barthélemy', code: 'BL', phoneNumberCode: '+590'},
    {name: 'Saint Helena', code: 'SH', phoneNumberCode: '+290'},
    {name: 'Saint Kitts and Nevis', code: 'KN', phoneNumberCode: '+1'},
    {name: 'Saint Lucia', code: 'LC', phoneNumberCode: '+1'}, {name: 'Saint Martin', code: 'MF', phoneNumberCode: '+1 599'},
    {name: 'Saint Pierre and Miquelon', code: 'PM', phoneNumberCode: '+508'},
    {name: 'Saint Vincent and the Grenadines', code: 'VC', phoneNumberCode: '+1'},
    {name: 'Samoa', code: 'WS', phoneNumberCode: '+685'}, {name: 'San Marino', code: 'SM', phoneNumberCode: '+378'},
    {name: 'Sao Tome and Principe', code: 'ST', phoneNumberCode: '+239'},
    {name: 'Saudi Arabia', code: 'SA', phoneNumberCode: '+966'}, {name: 'Senegal', code: 'SN', phoneNumberCode: '+221'},
    {name: 'Serbia', code: 'RS', phoneNumberCode: '+381'}, {name: 'Seychelles', code: 'SC', phoneNumberCode: '+248'},
    {name: 'Sierra Leone', code: 'SL', phoneNumberCode: '+232'}, {name: 'Singapore', code: 'SG', phoneNumberCode: '+65'},
    {name: 'Slovakia', code: 'SK', phoneNumberCode: '+421'}, {name: 'Slovenia', code: 'SI', phoneNumberCode: '+386'},
    {name: 'Solomon Islands', code: 'SB', phoneNumberCode: '+677'}, {name: 'Somalia', code: 'SO', phoneNumberCode: '+252'},
    {name: 'South Africa', code: 'ZA', phoneNumberCode: '+27'}, {name: 'South Korea', code: 'KR', phoneNumberCode: '+82'},
    {name: 'South Sudan', code: 'SS', phoneNumberCode: '+211'}, {name: 'Spain', code: 'ES', phoneNumberCode: '+34'},
    {name: 'Sri Lanka', code: 'LK', phoneNumberCode: '+94'}, {name: 'Sudan', code: 'SD', phoneNumberCode: '+249'},
    {name: 'Suriname', code: 'SR', phoneNumberCode: '+597'}, {name: 'Swaziland', code: 'SZ', phoneNumberCode: '+268'},
    {name: 'Sweden', code: 'SE', phoneNumberCode: '+46'}, {name: 'Switzerland', code: 'CH', phoneNumberCode: '+41'},
    {name: 'Syria', code: 'SY', phoneNumberCode: '+963'}, {name: 'Taiwan', code: 'TW', phoneNumberCode: '+886'},
    {name: 'Tajikistan', code: 'TJ', phoneNumberCode: '+992'}, {name: 'Tanzania', code: 'TZ', phoneNumberCode: '+255'},
    {name: 'Thailand', code: 'TH', phoneNumberCode: '+66'}, {name: 'Togo', code: 'TG', phoneNumberCode: '+228'},
    {name: 'Tokelau', code: 'TK', phoneNumberCode: '+690'}, {name: 'Trinidad and Tobago', code: 'TT', phoneNumberCode: '+1'},
    {name: 'Tunisia', code: 'TN', phoneNumberCode: '+216'}, {name: 'Turkey', code: 'TR', phoneNumberCode: '+90'},
    {name: 'Turkmenistan', code: 'TM', phoneNumberCode: '+993'}, {name: 'Tuvalu', code: 'TV', phoneNumberCode: '+688'},
    {name: 'Uganda', code: 'UG', phoneNumberCode: '+256'}, {name: 'Ukraine', code: 'UA', phoneNumberCode: '+380'},
    {name: 'United Arab Emirates', code: 'AE', phoneNumberCode: '+971'},
    {name: 'United Kingdom', code: 'GB', phoneNumberCode: '+44'}, {name: 'United States', code: 'US', phoneNumberCode: '+1'},
    {name: 'Uruguay', code: 'UY', phoneNumberCode: '+598'}, {name: 'Uzbekistan', code: 'UZ', phoneNumberCode: '+998'},
    {name: 'Vanuatu', code: 'VU', phoneNumberCode: '+678'}, {name: 'Vatican', code: 'VA', phoneNumberCode: '+39'},
    {name: 'Venezuela', code: 'VE', phoneNumberCode: '+58'}, {name: 'Vietnam', code: 'VN', phoneNumberCode: '+84'},
    {name: 'Western Sahara', code: 'EH', phoneNumberCode: '+212'}, {name: 'Yemen', code: 'YE', phoneNumberCode: '+967'},
    {name: 'Zambia', code: 'ZM', phoneNumberCode: '+260'}, {name: 'Zimbabwe', code: 'ZW', phoneNumberCode: '+263'}];
